# Site settings
title: Laboratory for Pattern Engineering
email: pattern@ducic.ac.in
description: > #
    Laboratory for Pattern Engineering.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pattern.ducic.ac.in" # the base hostname & protocol for your site
github_username:  prashnts

# Build settings
markdown: kramdown
permalink: pretty
